### ISSUE TITLE
Compatibilty  with atom 0.188.0 

### ISSUE THREAD

**Issue by hellboy81** [danielgtaylor/atom-api-blueprint-preview#21]
After upgrade to new `atom.io` version plug-in can not be loaded

```
**Atom Version**: 0.188.0
**System**: linux 3.13.0-35-generic
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.3.0

### Stack Trace

Failed to load the api-blueprint-preview package

```
At Module did not self-register.

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/local/.../.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/home/local/.../.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/local/../.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:4:10)
  at Object.<anonymous> (/home/local/.../.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/local/.../.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:4:27)
  at Object.<anonymous> (/home/local/.../.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:678:34)
  at /opt/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:460:30)
  at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:63:47)
  at /opt/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -2:24.9 command-palette:toggle (atom-text-editor.editor)
     -2:09.4 update-package-dependencies:update (atom-text-editor.editor)
     -2:00.2 editor:consolidate-selections (atom-text-editor.editor)
     -2:00.2 core:cancel (atom-text-editor.editor)
     -1:58.6 editor:consolidate-selections (atom-text-editor.editor)
     -1:58.6 core:cancel (atom-text-editor.editor)
     -1:43.9 command-palette:toggle (atom-text-editor.editor)
     -1:35.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:35.3 core:cancel (atom-text-editor.editor.mini)
     -0:38.5 core:backspace (atom-text-editor.editor.mini)
     -0:31.2 editor:select-to-first-character-of-line (atom-text-editor.editor.mini)
     -0:30.9 core:delete (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {},
  "api-blueprint-preview": {}
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.3.0
asciidoc-preview, v0.4.3
atom-jshint, v1.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.0
cucumber, v0.4.1
docblockr, v0.6.3
grunt-runner, v0.8.0
jsonlint, v1.0.2
language-asciidoc, v0.11.1
language-gherkin-german, v0.5.2
refactor, v0.4.1

# Dev
No dev packages
```

```

**Comment by danielgtaylor** [comment]
Looks like they must have changed something in a backward-incompatible way. I'll try to look into this when I get some time.

**Comment by danielgtaylor** [comment]
This has been fixed with the latest release. Let me know if it happens again.
