### ISSUE TITLE
Failed to load the api-blueprint-preview package

### ISSUE THREAD

**Issue by kuno** [danielgtaylor/atom-api-blueprint-preview#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.3.0

### Stack Trace

Failed to load the api-blueprint-preview package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/kuno/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/kuno/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "term",
      "terminal-status",
      "linter-rst"
    ]
  },
  "api-blueprint-preview": {}
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.3.0
atom-color-highlight, v3.0.8
atom-django, v0.2.1
auto-detect-indentation, v0.3.0
autocomplete-clang, v0.6.2
autocomplete-emojis, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
command-logger, v0.22.0
dart-tools, v0.8.9
dash, v1.1.0
editor-stats, v0.17.0
file-icons, v1.5.2
filetype-color, v0.1.4
git-log, v0.3.0
git-tab-status, v1.6.0
go-format, v1.0.7
go-plus, v3.3.2
indentation-indicator, v0.4.1
inline-autocomplete, v1.0.4
jshint, v1.3.0
language-applescript, v0.1.0
language-dart, v0.1.1
language-docker, v1.1.3
language-elixir, v0.3.4
language-erlang, v2.0.0
language-generic-config, v0.1.3
language-groovy, v0.3.0
language-haskell, v1.0.0
language-ini, v1.9.0
language-python-django-templates, v0.1.0
language-rust, v0.4.2
language-swift, v0.3.0
language-viml, v0.2.0
linter, v0.12.0
linter-clang, v2.25.1
linter-coffeelint, v0.2.1
linter-cpplint, v0.1.3
linter-elixirc, v0.2.1
linter-flake8, v1.3.0
linter-golint, v0.2.0
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-pep8, v0.1.0
linter-python-pep8, v0.2.0
linter-shellcheck, v0.0.7
linter-swiftc, v0.1.1
minimap, v4.7.2
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
pretty-json, v0.3.2
project-manager, v1.15.5
script, v2.18.0
space-tab, v0.1.0
tabs-to-spaces, v0.9.2
trailing-spaces, v0.2.4
travis-ci-status, v0.13.0
view-tail-large-files, v0.1.13
vim-mode, v0.42.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by lxfontes** [comment]
reinstalling it fixed.
`apm install api-blueprint-preview`

**Comment by lxfontes** [comment]
This is due to a binary inside pathwatcher
```javascript
binding = require('../build/Release/pathwatcher.node');
```

**Comment by jinmatt** [comment]
+1 @lxfontes : reinstalling fixed the problem
```
$ apm uninstall api-blueprint-preview
$ apm install api-blueprint-preview
```

**Comment by danielgtaylor** [comment]
I believe this is all fixed now, please let me know if you run into it again!
