### ISSUE TITLE
Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.To subscribe to events on an Atom object, use an explicit event-subscriptionmethod (starting with ::onDid* or ::onWill*).To collect multiple subscription objects for later disposal, add them to a`CompositeDisposable` instance:https://atom.io/docs/api/v0.150.0/CompositeDisposableCall `.dispose()` on your `CompositeDisposable` in this view's `::detached` hook.

### ISSUE THREAD

**Issue by jfairley** [danielgtaylor/atom-api-blueprint-preview#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.3.2

### Stack Trace

Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.

To subscribe to events on an Atom object, use an explicit event-subscription
method (starting with ::onDid* or ::onWill*).

To collect multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance:
https://atom.io/docs/api/v0.150.0/CompositeDisposable

Call `.dispose()` on your `CompositeDisposable` in this view's `::detached` hook.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576

Error: The `::subscribe` method is no longer available on SpacePen views.

To subscribe to events on an Atom object, use an explicit event-subscription
method (starting with ::onDid* or ::onWill*).

To collect multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance:
https://atom.io/docs/api/v0.150.0/CompositeDisposable

Call `.dispose()` on your `CompositeDisposable` in this view's `::detached` hook.
  at ApiBlueprintPreviewView.View.subscribe (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576:11)
  at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.handleEvents (/Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:60:6)
  at /Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:41:10
  at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.resolveEditor (/Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:48:7)
  at new ApiBlueprintPreviewView (/Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:22:8)
  at /Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:27:13
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:366:19)
  at Object.module.exports.toggle (/Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:46:20)
  at atom-workspace.<anonymous> (/Users/jfairley/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:19:8)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:00.8.0 api-blueprint-preview:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "greti-syntax"
    ]
  },
  "api-blueprint-preview": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
api-blueprint-preview, v0.3.2
editorconfig, v1.0.0
greti-syntax, v0.5.4
language-docker, v1.1.3
language-flex, v0.2.0
linter, v0.12.6
minimap, v4.9.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by danielgtaylor** [comment]
@jfairley please try to update to the latest release from a few minutes ago. It's a major update to sync with the upstream preview plugin and remove all these damn deprecations.

**Comment by danielgtaylor** [comment]
I'm closing this for now as I can no longer reproduce it. Please update and try again, then if there is still an problem please re-open this issue.

**Comment by jfairley** [comment]
That fixed it. Thanks!
