### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by marchuguet** [danielgtaylor/atom-api-blueprint-preview#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.3
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.5.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/marchuguet/.atom/packages/api-blueprint-preview/lib/renderer.coffee:39

TypeError: undefined is not a function
    at resolveImagePaths (/Users/marchuguet/.atom/packages/api-blueprint-preview/lib/renderer.coffee:71:34)
    at /Users/marchuguet/.atom/packages/api-blueprint-preview/lib/renderer.coffee:64:31
    at ChildProcess.exithandler (child_process.js:740:7)
    at ChildProcess.emit (events.js:119:17)
    at maybeClose (child_process.js:1013:16)
    at Socket.<anonymous> (child_process.js:1181:11)
    at Socket.emit (events.js:116:17)
    at Pipe.close (net.js:477:12)
```

### Commands

```
     -0:02.4 api-blueprint-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.5.1
language-api-blueprint, v1.0.1

# Dev
No dev packages
```

**Comment by gEndelf** [comment]
+1 

---

Reproduce:

1. open **test_api.md** (attached below)
2. press **Ctrl+Shift+a**

```
FORMAT: 1A
HOST: https://api.example.com

# Group Notes
Group description (also with *Markdown*)

## Note List [/notes]
Note list description

+ Even
+ More
+ Markdown

+ Model

    + Headers

            Content-Type: application/json
            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            [
                {
                    "id": 1,
                    "title": "Grocery list",
                    "body": "Buy milk"
                },
                {
                    "id": 2,
                    "title": "TODO",
                    "body": "Fix garage door"
                }
            ]

### Get Notes [GET]
Get a list of notes.

+ Response 200

    [Note List][]
```

**Comment by danielgtaylor** [comment]
Please try installing Aglio 2.0.2 (the latest release) and the latest version of the plugin. I am not able to reproduce this issue with those.
