### ISSUE TITLE
Fails to install in Atom 1.2.1

### ISSUE THREAD

**Issue by phw** [danielgtaylor/atom-api-blueprint-preview#45]
Installing in Atom 1.2.1 fails for me with the following error output:

```
> runas@2.0.0 install /tmp/apm-install-dir-1151015-9033-1mgp2qd/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Verzeichnis „/tmp/apm-install-dir-1151015-9033-1mgp2qd/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas/build“ wird betreten
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: die Regel für Ziel „Release/obj.target/runas/src/main.o“ scheiterte
make: Verzeichnis „/tmp/apm-install-dir-1151015-9033-1mgp2qd/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas/build“ wird verlassen

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
In file included from ../src/main.cc:1:0:
../../nan/nan.h:260:25: Fehler: Redefinition von »template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)«
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:255:25: Anmerkung: »template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)« wurde bereits hier deklariert
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:660:13: Fehler: »node::smalloc« wurde nicht deklariert
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:660:35: Fehler: expected »,« or »...« before »callback«
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)«:
../../nan/nan.h:664:50: Fehler: »callback« wurde in diesem Gültigkeitsbereich nicht definiert
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:664:60: Fehler: »hint« wurde in diesem Gültigkeitsbereich nicht definiert
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)«:
../../nan/nan.h:671:67: Fehler: keine passende Funktion für Aufruf von »New(v8::Isolate*, const char*&, uint32_t&)«
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/phw/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:41:40: Anmerkung: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <nahe Übereinstimmung>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/phw/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:41:40: Anmerkung:   Umwandlung von Argument 3 wäre unzulässig:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: Fehler: ungültige Umwandlung von »uint32_t {aka unsigned int}« in »node::encoding« [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/main.cc:1:
/home/phw/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:53:40: Anmerkung: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <nahe Übereinstimmung>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/phw/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:53:40: Anmerkung:   Umwandlung von Argument 2 wäre unzulässig:
In file included from ../src/main.cc:1:0:
../../nan/nan.h:671:67: Fehler: ungültige Umwandlung von »const char*« in »char*« [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(uint32_t)«:
../../nan/nan.h:675:29: Fehler: »node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))« konnte nicht von »v8::MaybeLocal<v8::Object>« nach »v8::Local<v8::Object>« umgewandelt werden
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In Funktion »v8::Local<v8::Object> NanBufferUse(char*, uint32_t)«:
../../nan/nan.h:682:12: Fehler: »Use« ist kein Element von »node::Buffer«
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.5-1-ARCH
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1151015-9033-1mgp2qd/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/phw/.atom/.apm/.apmrc" "--userconfig" "/home/phw/.atom/.apmrc" "install" "/tmp/d-1151015-9033-5njyvj/package.tgz" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1151015-9033-1mgp2qd/npm-debug.log
```

**Comment by davibe** [comment]
same here

**Comment by GrimR3** [comment]
Same on Windows 10
```dosini
> runas@2.0.0 install C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\grimr\AppData\Local\atom\app-1.2.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
  main.cc
  runas_win.cc
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(262): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(255) : see declaration of '_NanEnsureLocal'
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(660): error C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(660): error C2039: 'FreeCallback' : is not a member of 'node' (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(660): error C2061: syntax error : identifier 'FreeCallback' (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(664): error C2065: 'callback' : undeclared identifier (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(664): error C2065: 'hint' : undeclared identifier (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(671): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\grimr\.atom\.node-gyp\.node-gyp\0.34.0\src\node_buffer.h(53): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\grimr\.atom\.node-gyp\.node-gyp\0.34.0\src\node_buffer.h(41): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(675): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(682): error C2039: 'Use' : is not a member of 'node::Buffer' (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(682): error C3861: 'Use': identifier not found (..\src\main.cc) [C:\Users\grimr\AppData\Local\Temp\apm-install-dir-1151016-1760-x6tk0x\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\grimr\\AppData\\Local\\atom\\app-1.2.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\grimr\\AppData\\Local\\atom\\app-1.2.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\grimr\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\grimr\\.atom\\.apmrc" "install" "C:\\Users\\grimr\\AppData\\Local\\Temp\\d-1151016-1760-1aupm8h\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

**Comment by jamesbrooks** [comment]
:+1: to this issue

**Comment by ecstasy2** [comment]
+1

**Comment by michael-kuk** [comment]
+1

**Comment by kaidokert** [comment]
Changing package.json from :
    "pathwatcher": "^4.3",
to
    "pathwatcher": "^6.0.0",

Seemed to make it install, not sure if its working properly yet

**Comment by lazutkin** [comment]
+1

**Comment by hg-jt** [comment]
+1

**Comment by LinusU** [comment]
Same problem here

**Comment by joliva-ob** [comment]
+1

**Comment by Ustice** [comment]
This is the error that I get when trying to install on OS X 10.10.5 with Atom 1.2.4.

````
> runas@2.0.0 install /private/var/folders/fh/f5ljrb8905n6_xbwfyrrdstm0000gp/T/apm-install-dir-1151030-3052-16povvt/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o

npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
In file included from ../src/main.cc:1:
../../nan/nan.h:260:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:255:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:660:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:671:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:41:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:53:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:38:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:46:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/main.cc:1:
../../nan/nan.h:675:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/main.cc:1:
../../nan/nan.h:682:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node.h:42:
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:413:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node.h:42:
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:423:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node.h:42:
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1513:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/src/node.h:42:
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jkleinberg/.atom/.node-gyp/.node-gyp/0.34.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1631:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/fh/f5ljrb8905n6_xbwfyrrdstm0000gp/T/apm-install-dir-1151030-3052-16povvt/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jkleinberg/.atom/.apm/.apmrc" "--userconfig" "/Users/jkleinberg/.atom/.apmrc" "install" "/private/var/folders/fh/f5ljrb8905n6_xbwfyrrdstm0000gp/T/d-1151030-3052-hwnjeu/package.tgz" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/fh/f5ljrb8905n6_xbwfyrrdstm0000gp/T/apm-install-dir-1151030-3052-16povvt/npm-debug.log
````

**Comment by samekmichal** [comment]
Any updates on that issue?

**Comment by Helias-Criouet** [comment]
Same error on Atom 1.3.1 still. @kaidokert any idea?

**Comment by kaidokert** [comment]
Uh, not sure. I'm using the patched version here with no problems - installed in development mode. Or someone could try and publish a temporary fixed package with apm

**Comment by blizzardzheng** [comment]
any solution for this issue ？

**Comment by danielgtaylor** [comment]
Please update to the 0.7.0 release, which works in Atom 1.2+ :+1:
