### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 46, got 44.

### ISSUE THREAD

**Issue by ecstasy2** [danielgtaylor/atom-api-blueprint-preview#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.10.5
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Module version mismatch. Expected 46, got 44.

```
At ATOM_SHELL_ASAR.js:137

Error: Module version mismatch. Expected 46, got 44.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/diallo/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/diallo/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:207:4)
```

### Commands

```
     -3:25.4.0 api-blueprint-preview:toggle (atom-text-editor.editor.is-focused)
  6x -2:44.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:01.0 api-blueprint-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.6.0
language-api-blueprint, v1.0.2
linter, v1.11.2
linter-eslint, v5.2.0

# Dev
No dev packages
```

**Comment by danielgtaylor** [comment]
@ecstasy2 please try installing again with the latest version (0.7.0) and let me know if you still have issues. It should have fixed some incompatibilities.
