### ISSUE TITLE
Fails to install on Atom 1.3.0 on Mac OSX 10.11.1

### ISSUE THREAD

**Issue by dijitalmunky** [danielgtaylor/atom-api-blueprint-preview#49]
When installing through the UI in Atom, the following error occurs:

```

> runas@2.0.0 install /private/var/folders/jz/dbbxg8b101g2w09qypdcfpc80000gn/T/apm-install-dir-1151110-24060-1px21bs/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
In file included from ../src/main.cc:1:
../../nan/nan.h:260:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:255:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:660:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:671:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:41:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:53:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:38:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:46:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/main.cc:1:
../../nan/nan.h:675:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/main.cc:1:
../../nan/nan.h:682:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:413:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:423:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1513:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chrisroe-Anow/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1631:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)

gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/jz/dbbxg8b101g2w09qypdcfpc80000gn/T/apm-install-dir-1151110-24060-1px21bs/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/chrisroe-Anow/.atom/.apm/.apmrc" "--userconfig" "/Users/chrisroe-Anow/.atom/.apmrc" "install" "/private/var/folders/jz/dbbxg8b101g2w09qypdcfpc80000gn/T/d-1151110-24060-wxzb4d/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/jz/dbbxg8b101g2w09qypdcfpc80000gn/T/apm-install-dir-1151110-24060-1px21bs/npm-debug.log
```

**Comment by sebdah** [comment]
+1

**Comment by fkrauthan** [comment]
Same issue for me

**Comment by spieker** [comment]
+1

**Comment by lintide** [comment]
+1

**Comment by higumachan** [comment]
+1

**Comment by katzien** [comment]
+1

**Comment by zdne** [comment]
I believe this should be fixed with #48

**Comment by danielgtaylor** [comment]
This should now be fixed with the 0.7.0 release. I had to use a rebuild button in Atom to get it working, but after that it all worked.

**Comment by katzien** [comment]
Thanks everyone, works for me now as well :)

**Comment by furryfury** [comment]
Help!!!! I want this downloaded nowwwww

Last login: Wed Feb 17 17:12:06 on ttys000
/Applications/Atom.app/Contents/MacOS/Atom ; exit;
mkdir: /Users/dopeboyfresh/.bash_sessions: Operation not permitted
touch: /Users/dopeboyfresh/.bash_sessions/B028012D-B3BE-4616-8C78-31C4D71FEEA3.historynew: No such file or directory
Rebeccas-MacBook-Pro:~ dopeboyfresh$ /Applications/Atom.app/Contents/MacOS/Atom ; exit;
2016-02-17 17:22:11.868 Atom[1402:68882] EPERM: operation not permitted, mkdir '/Users/dopeboyfresh/.atom'
2016-02-17 17:22:11.875 Atom[1402:68882] Error: EPERM: operation not permitted, mkdir '/Users/dopeboyfresh/.atom'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:343:23)
    at Config.module.exports.Config.initializeConfigDirectory (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:427:10)
    at Config.module.exports.Config.load (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:412:12)
    at new AutoUpdateManager (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/auto-update-manager.js:50:19)
    at new AtomApplication (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:102:32)
    at createAtomApplication (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

How do i solve this issue ?!?!
