### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getStyleElements' of undefined

### ISSUE THREAD

**Issue by ghost** [danielgtaylor/atom-api-blueprint-preview#52]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getStyleElements' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:81

TypeError: Cannot read property 'getStyleElements' of undefined
    at atom-styles.StylesElement.contextChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:81:32)
    at atom-styles.StylesElement.attributeChangedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/styles-element.js:56:21)
    at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.getTextEditorStyles (/Users/lookuphq/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:194:22)
    at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.getApiBlueprintPreviewCSS (/Users/lookuphq/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:216:16)
    at /Users/lookuphq/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:280:42
    at /Users/lookuphq/.atom/packages/api-blueprint-preview/lib/renderer.coffee:39:5
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  2x -0:50.7.0 core:save-as (button.btn.btn-primary.btn-xs)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
api-blueprint-preview, v0.7.0

# Dev
No dev packages
```

**Comment by dbilovd** [comment]
Happens on Atom Version: 1.8.0 also.

**Comment by malsec-dev** [comment]
Same here, Atom version 1.10.2
