### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by shenjinxi** [danielgtaylor/atom-api-blueprint-preview#60]
> runas@3.1.1 install /private/var/folders/kt/4_0_tq6d1nn202stvz2wt1zc0000gn/T/apm-install-dir-11632-23996-181fmfx/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
make: **\* No rule to make target `../../../../../../../../../../../../../../Applications/Atom', needed by`Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/kt/4_0_tq6d1nn202stvz2wt1zc0000gn/T/apm-install-dir-11632-23996-181fmfx/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/XXX/.atom/.apm/.apmrc" "--userconfig" "/Users/XXX/.atom/.apmrc" "install" "/private/var/folders/kt/4_0_tq6d1nn202stvz2wt1zc0000gn/T/d-11632-23996-1ufeosk/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/kt/4_0_tq6d1nn202stvz2wt1zc0000gn/T/apm-install-dir-11632-23996-181fmfx/npm-debug.log

**Comment by MistShi** [comment]
> runas@3.1.1 install /private/var/folders/f5/pc4l4pn53f312cqpwb3tj7wm0000gn/T/apm-install-dir-116625-14361-1uwkl0n/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
make: **\* No rule to make target `../../../../../../../../../../../../../../Applications/Atom', needed by`Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/f5/pc4l4pn53f312cqpwb3tj7wm0000gn/T/apm-install-dir-116625-14361-1uwkl0n/node_modules/api-blueprint-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/shark/.atom/.apm/.apmrc" "--userconfig" "/Users/shark/.atom/.apmrc" "install" "/private/var/folders/f5/pc4l4pn53f312cqpwb3tj7wm0000gn/T/d-116625-14361-1i2o9y7/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/f5/pc4l4pn53f312cqpwb3tj7wm0000gn/T/apm-install-dir-116625-14361-1uwkl0n/npm-debug.log
