### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by fengwangjie** [danielgtaylor/atom-api-blueprint-preview#68]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package 0.7.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:457

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/administrator/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-api-blueprint-preview-0.7.0/lib/api-blueprint-preview-view.coffee:4:24)
    at /packages/atom-api-blueprint-preview-0.7.0/lib/api-blueprint-preview-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at isApiBlueprintPreviewView (/packages/atom-api-blueprint-preview-0.7.0/lib/main.coffee:11:30)
    at Object.toggle (/packages/atom-api-blueprint-preview-0.7.0/lib/main.coffee:79:8)
    at /packages/atom-api-blueprint-preview-0.7.0/lib/main.coffee:43:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:27.4.0 api-blueprint-preview:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
```

**Comment by mehdimusavi** [comment]
Hello everyone
I get some like errors too,

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package 0.7.0


### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:472

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-api-blueprint-preview/lib/api-blueprint-preview-view.coffee:4:24)
    at /packages/atom-api-blueprint-preview/lib/api-blueprint-preview-view.coffee:1:1)
    at /packages/atom-api-blueprint-preview/lib/api-blueprint-preview-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.19.7/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at isApiBlueprintPreviewView (/packages/atom-api-blueprint-preview/lib/main.coffee:11:30)
    at Object.toggle (/packages/atom-api-blueprint-preview/lib/main.coffee:79:8)
    at /packages/atom-api-blueprint-preview/lib/main.coffee:43:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:25.5.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:44.2.0 core:backspace (input.hidden-input)
  2x -2:36.4.0 core:paste (input.hidden-input)
     -2:04.8.0 application:add-project-folder (a.)
     -1:01.4.0 tree-view:show-current-file-in-file-manager (div.line)
     -0:37.5.0 api-blueprint-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
language-api-blueprint 1.0.2  
```

how i can solve the this error?
