### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed./\?\$ATOM_HOME\packa...

### ISSUE THREAD

**Issue by tannongchun** [danielgtaylor/atom-api-blueprint-preview#70]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package 0.7.0

### Stack Trace

Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\92039\.atom\packages\api-blueprint-preview\node_modules\pathwatcher\build\Release\pathwatcher.node

```
At ELECTRON_ASAR.js:173

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\92039\.atom\packages\api-blueprint-preview\node_modules\pathwatcher\build\Release\pathwatcher.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:4:13)
    at /packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:266:4)
    at /packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:268:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:8:10)
    at /packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:1:1)
    at /packages/api-blueprint-preview/lib/api-blueprint-preview-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at isApiBlueprintPreviewView (/packages/atom-api-blueprint-preview/lib/main.coffee:20:33)
    at Object.toggle (/packages/atom-api-blueprint-preview/lib/main.coffee:109:11)
    at /packages/atom-api-blueprint-preview/lib/main.coffee:54:26)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:20.3.0 api-blueprint-preview:toggle (div.package-detail.panels-item)
     -8:04.4.0 tabs:close-tab (div.title.icon.icon-tools)
  2x -7:57.5.0 linter-api-blueprint:parse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:33.4.0 package-generator:generate-package (input.hidden-input)
  2x -5:41.1.0 api-blueprint-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
busy-signal 1.4.3 
intentions 1.1.5 
language-api-blueprint 1.0.2 
linter 2.2.0 
linter-api-blueprint 0.4.0 
linter-ui-default 1.6.10 
```

**Comment by tannongchun** [comment]
how fix it ?
