### ISSUE TITLE
Installing “api-blueprint-preview@0.7.0” failed

### ISSUE THREAD

**Issue by michael-damatov** [danielgtaylor/atom-api-blueprint-preview#71]
> > runas@3.1.1 install C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi\node_modules\api-blueprint-preview\node_modules\runas
> > node-gyp rebuild
> 
> 
> C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi\node_modules\api-blueprint-preview\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\...\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\...\AppData\Local\atom\app-1.23.3\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
> C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi
> `-- (empty)
> 
> 
> npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
> npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
> npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
> gyp ERR! configure error 
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\...\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
> gyp ERR! stack     at C:\Users\...\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
> gyp ERR! stack     at C:\Users\...\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Users\\...\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\...\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi\node_modules\api-blueprint-preview\node_modules\runas
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi\package.json'
> npm WARN apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi No description
> npm WARN apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi No repository field.
> npm WARN apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi No README data
> npm WARN apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi No license field.
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Users\\...\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\...\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\...\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\...\\.atom\\.apmrc" "install" "C:\\Users\\...\\AppData\\Local\\Temp\\d-11818-16452-g3y5jo.aou7bvs4i\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style" "--msvs_version=2015"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! runas@3.1.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the runas package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs runas
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls runas
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\...\AppData\Local\Temp\apm-install-dir-11818-16452-cvbjd7.jv5kk8d7vi\npm-debug.log
> npm ERR! code 1

Do I miss anything?

**Comment by xunchangguo** [comment]
i hava same error. said need python. but which version of python is need?

**Comment by zenozhang26** [comment]
It looks like you have no python in your computer, if you have installed python3, you need to install python2.
Or if you have both two versions of python, then I solved this problem under another issue:
https://github.com/danielgtaylor/atom-api-blueprint-preview/issues/38#issuecomment-430852308
